export default {
    Math: [
        {
            name: 'overline',
            value: '\\overline{ab}',
            icon: 'src/assets/latex/math/overline.png'
        }, {
            name: 'sqrt',
            value: '\\sqrt{ab}',
            icon: 'src/assets/latex/math/sqrt.png'
        }, {
            name: 'f',
            value: 'f\'',
            icon: 'src/assets/latex/math/fdash.png'
        }, {
            name: 'x',
            value: 'x^{k}',
            icon: 'src/assets/latex/math/xpk.png'
        }, {
            name: 'limit',
            value: '\\lim_{a \\rightarrow b}',
            icon: 'src/assets/latex/math/limit.png'
        }, {
            name: 'matrix',
            value: '\\begin{bmatrix}a & b \\\\c & d \\end{bmatrix}',
            icon: 'src/assets/latex/math/matrix.png'
        }, {
            name: 'para',
            value: '\\big(a\\big)',
            icon: 'src/assets/latex/math/para.png'
        }, {
            name: 'int',
            value: '\\int_a^b x',
            icon: 'src/assets/latex/math/int.png'
        }, {
            name: 'sum',
            value: '\\sum_a^b x',
            icon: 'src/assets/latex/math/sum.png'
        }, {
            name: 'prod',
            value: '\\prod_a^b x',
            icon: 'src/assets/latex/math/prod.png'
        }, {
            name: 'bigcap',
            value: '\\bigcap_a^b x',
            icon: 'src/assets/latex/math/bigcap.png'
        }, {
            name: 'bigvee',
            value: '\\bigvee_a^b x',
            icon: 'src/assets/latex/math/bigvee.png'
        }, {
            name: 'bigotimes',
            value: '\\bigotimes',
            icon: 'src/assets/latex/math/bigotimes.png'
        }, {
            name: 'underline',
            value: '\\underline{ab}',
            icon: 'src/assets/latex/math/underline.png'
        }, {
            name: 'sqrtn',
            value: '\\sqrt[n]{ab}',
            icon: 'src/assets/latex/math/sqrtn.png'
        }, {
            name: 'frac',
            value: '\\frac{a}{b}',
            icon: 'src/assets/latex/math/frac.png'
        }, {
            name: 'xuk',
            value: 'x_{k}',
            icon: 'src/assets/latex/math/xuk.png'
        }, {
            name: 'partial',
            value: '\\frac{\\partial^nf}{\\partial x^n}',
            icon: 'src/assets/latex/math/partial.png'
        }, {
            name: 'select',
            value: 'x =\\begin{cases}a & x = 0\\\\b & x > 0\\end{cases}',
            icon: 'src/assets/latex/math/select.png'
        }, {
            name: 'curly',
            value: '\\big\\{a\\big\\}',
            icon: 'src/assets/latex/math/curly.png'
        }, {
            name: 'oint',
            value: '\\oint_a^b x',
            icon: 'src/assets/latex/math/oint.png'
        }, {
            name: 'bigsqcup',
            value: '\\bigsqcup_a^b x',
            icon: 'src/assets/latex/math/bigsqcup.png'
        }, {
            name: 'coprod',
            value: '\\coprod_a^b x',
            icon: 'src/assets/latex/math/coprod.png'
        }, {
            name: 'bigcup',
            value: '\\bigcup_a^b x',
            icon: 'src/assets/latex/math/bigcup.png'
        }, {
            name: 'bigvee',
            value: '\\bigwedge_a^b x',
            icon: 'src/assets/latex/math/bigvee.png'
        }, {
            name: 'bigoplus',
            value: '\\bigoplus',
            icon: 'src/assets/latex/math/bigoplus.png'
        }
    ],
    Greek: [
        {
            name: 'alpha',
            value: '\\alpha',
            icon: 'src/assets/latex/greek/alpha.png'
        }, {
            name: 'beta',
            value: '\\beta',
            icon: 'src/assets/latex/greek/beta.png'
        }, {
            name: 'gamma',
            value: '\\gamma',
            icon: 'src/assets/latex/greek/gamma.png'
        }, {
            name: 'delta',
            value: '\\delta',
            icon: 'src/assets/latex/greek/delta.png'
        }, {
            name: 'epsilon',
            value: '\\epsilon',
            icon: 'src/assets/latex/greek/epsilon.png'
        }, {
            name: 'varepsilon',
            value: '\\varepsilon',
            icon: 'src/assets/latex/greek/varepsilon.png'
        }, {
            name: 'zeta',
            value: '\\zeta',
            icon: 'src/assets/latex/greek/zeta.png'
        }, {
            name: 'eta',
            value: '\\eta',
            icon: 'src/assets/latex/greek/eta.png'
        }, {
            name: 'theta',
            value: '\\theta',
            icon: 'src/assets/latex/greek/theta.png'
        }, {
            name: 'vartheta',
            value: '\\vartheta',
            icon: 'src/assets/latex/greek/vartheta.png'
        }, {
            name: 'kappa',
            value: '\\kappa',
            icon: 'src/assets/latex/greek/kappa.png'
        }, {
            name: 'lambda',
            value: '\\lambda',
            icon: 'src/assets/latex/greek/lambda.png'
        }, {
            name: 'mu',
            value: '\\mu',
            icon: 'src/assets/latex/greek/mu.png'
        }, {
            name: 'nu',
            value: '\\nu',
            icon: 'src/assets/latex/greek/nu.png'
        }, {
            name: 'Gammabig',
            value: '\\Gamma',
            icon: 'src/assets/latex/greek/Gammabig.png'
        }, {
            name: 'Deltabig',
            value: '\\Delta',
            icon: 'src/assets/latex/greek/Deltabig.png'
        }, {
            name: 'Thetabig',
            value: '\\Theta',
            icon: 'src/assets/latex/greek/Thetabig.png'
        }, {
            name: 'Lambdabig',
            value: '\\Lambda',
            icon: 'src/assets/latex/greek/Lambdabig.png'
        }, {
            name: 'Xibig',
            value: '\\Xi',
            icon: 'src/assets/latex/greek/Xibig.png'
        }, {
            name: 'Pibig',
            value: '\\Pi',
            icon: 'src/assets/latex/greek/Pibig.png'
        }, {
            name: 'xi',
            value: '\\xi',
            icon: 'src/assets/latex/greek/xi.png'
        }, {
            name: 'o',
            value: ' o',
            icon: 'src/assets/latex/greek/o.png'
        }, {
            name: 'pi',
            value: '\\pi',
            icon: 'src/assets/latex/greek/pi.png'
        }, {
            name: 'varpi',
            value: '\\varpi',
            icon: 'src/assets/latex/greek/varpi.png'
        }, {
            name: 'rho',
            value: '\\rho',
            icon: 'src/assets/latex/greek/rho.png'
        }, {
            name: 'varrho',
            value: '\\varrho',
            icon: 'src/assets/latex/greek/varrho.png'
        }, {
            name: 'sigma',
            value: '\\sigma',
            icon: 'src/assets/latex/greek/sigma.png'
        }, {
            name: 'varsigma',
            value: '\\varsigma',
            icon: 'src/assets/latex/greek/varsigma.png'
        }, {
            name: 'tau',
            value: '\\tau',
            icon: 'src/assets/latex/greek/tau.png'
        }, {
            name: 'upsilon',
            value: '\\upsilon',
            icon: 'src/assets/latex/greek/upsilon.png'
        }, {
            name: 'phi',
            value: '\\phi',
            icon: 'src/assets/latex/greek/phi.png'
        }, {
            name: 'varphi',
            value: '\\varphi',
            icon: 'src/assets/latex/greek/varphi.png'
        }, {
            name: 'chi',
            value: '\\chi',
            icon: 'src/assets/latex/greek/chi.png'
        }, {
            name: 'psi',
            value: '\\psi',
            icon: 'src/assets/latex/greek/psi.png'
        }, {
            name: 'omega',
            value: '\\omega',
            icon: 'src/assets/latex/greek/omega.png'
        }, {
            name: 'Sigmabig',
            value: '\\Sigma',
            icon: 'src/assets/latex/greek/Sigmabig.png'
        }, {
            name: 'Upsilonbig',
            value: '\\Upsilon',
            icon: 'src/assets/latex/greek/Upsilonbig.png'
        }, {
            name: 'Phibig',
            value: '\\Phi',
            icon: 'src/assets/latex/greek/Phibig.png'
        }, {
            name: 'Psibig',
            value: '\\Psi',
            icon: 'src/assets/latex/greek/Psibig.png'
        }, {
            name: 'Omegabig',
            value: '\\Omega',
            icon: 'src/assets/latex/greek/Omegabig.png'
        }

    ],
    Relations: [
        {
            name: 'leq',
            value: '\\leq',
            icon: 'src/assets/latex/relations/leq.png'
        }, {
            name: 'prec',
            value: '\\prec',
            icon: 'src/assets/latex/relations/prec.png'
        }, {
            name: 'preceq',
            value: '\\preceq',
            icon: 'src/assets/latex/relations/preceq.png'
        }, {
            name: 'll',
            value: '\\ll',
            icon: 'src/assets/latex/relations/ll.png'
        }, {
            name: 'subset',
            value: '\\subset',
            icon: 'src/assets/latex/relations/subset.png'
        }, {
            name: 'subseteq',
            value: '\\subseteq',
            icon: 'src/assets/latex/relations/subseteq.png'
        }, {
            name: 'sqsubset',
            value: '\\sqsubset',
            icon: 'src/assets/latex/relations/sqsubset.png'
        }, {
            name: 'sqsubseteq',
            value: '\\sqsubseteq',
            icon: 'src/assets/latex/relations/sqsubseteq.png'
        }, {
            name: 'in',
            value: '\\in',
            icon: 'src/assets/latex/relations/in.png'
        }, {
            name: 'vdash',
            value: '\\vdash>',
            icon: 'src/assets/latex/relations/vdash.png'
        }, {
            name: 'gt',
            value: '>',
            icon: 'src/assets/latex/relations/gt.png'
        }, {
            name: 'Join',
            value: '\\Join',
            icon: 'src/assets/latex/relations/Join.png'
        }, {
            name: 'smile',
            value: '\\smile',
            icon: 'src/assets/latex/relations/smile.png'
        }, {
            name: 'sim',
            value: '\\sim',
            icon: 'src/assets/latex/relations/sim.png'
        }, {
            name: 'asymp',
            value: '\\asymp',
            icon: 'src/assets/latex/relations/asymp.png'
        }, {
            name: 'equiv',
            value: '\\equiv',
            icon: 'src/assets/latex/relations/equiv.png'
        }, {
            name: 'mid',
            value: '\\mid',
            icon: 'src/assets/latex/relations/mid.png'
        }, {
            name: 'neq',
            value: '\\neq',
            icon: 'src/assets/latex/relations/neq.png'
        }, {
            name: 'perp',
            value: '\\perp',
            icon: 'src/assets/latex/relations/perp.png'
        }, {
            name: 'colon',
            value: ':',
            icon: 'src/assets/latex/relations/colon.png'
        }, {
            name: 'rhd',
            value: '\\rhd',
            icon: 'src/assets/latex/relations/rhd.png'
        }, {
            name: 'unrhd',
            value: '\\unrhd',
            icon: 'src/assets/latex/relations/unrhd.png'
        }, {
            name: 'geq',
            value: '\\geq',
            icon: 'src/assets/latex/relations/geq.png'
        }, {
            name: 'succ',
            value: '\\succ',
            icon: 'src/assets/latex/relations/succ.png'
        }, {
            name: 'succeq',
            value: '\\succeq',
            icon: 'src/assets/latex/relations/succeq.png'
        }, {
            name: 'gg',
            value: '\\gg',
            icon: 'src/assets/latex/relations/gg.png'
        }, {
            name: 'supset',
            value: '\\supset',
            icon: 'src/assets/latex/relations/supset.png'
        }, {
            name: 'supseteq',
            value: '\\supseteq',
            icon: 'src/assets/latex/relations/supseteq.png'
        }, {
            name: 'sqsupset',
            value: '\\sqsupset',
            icon: 'src/assets/latex/relations/sqsupset.png'
        }, {
            name: 'sqsupseteq',
            value: '\\sqsupseteq',
            icon: 'src/assets/latex/relations/sqsupseteq.png'
        }, {
            name: 'ni',
            value: '\\ni',
            icon: 'src/assets/latex/relations/ni.png'
        }, {
            name: 'dashv',
            value: '\\dashv',
            icon: 'src/assets/latex/relations/dashv.png'
        }, {
            name: 'lt',
            value: '<',
            icon: 'src/assets/latex/relations/lt.png'
        }, {
            name: 'bowtie',
            value: '\\bowtie',
            icon: 'src/assets/latex/relations/bowtie.png'
        }, {
            name: 'frown',
            value: '\\frown',
            icon: 'src/assets/latex/relations/frown.png'
        }, {
            name: 'simeq',
            value: '\\simeq',
            icon: 'src/assets/latex/relations/simeq.png'
        }, {
            name: 'approx',
            value: '\\approx',
            icon: 'src/assets/latex/relations/approx.png'
        }, {
            name: 'cong',
            value: '\\cong',
            icon: 'src/assets/latex/relations/cong.png'
        }, {
            name: 'parallel',
            value: '\\parallel',
            icon: 'src/assets/latex/relations/parallel.png'
        }, {
            name: 'doteq',
            value: '\\doteq',
            icon: 'src/assets/latex/relations/doteq.png'
        }, {
            name: 'models',
            value: '\\models',
            icon: 'src/assets/latex/relations/models.png'
        }, {
            name: 'propto',
            value: '\\propto',
            icon: 'src/assets/latex/relations/propto.png'
        }, {
            name: 'lhd',
            value: '\\lhd',
            icon: 'src/assets/latex/relations/lhd.png'
        }, {
            name: 'unlhd',
            value: '\\unlhd',
            icon: 'src/assets/latex/relations/unlhd.png'
        }
    ],
    Logic: [
        {
            name: 'hat',
            value: '\\hat{a}',
            icon: 'src/assets/latex/logic/hat.png'
        }, {
            name: 'acute',
            value: '\\acute{a}',
            icon: 'src/assets/latex/logic/acute.png'
        }, {
            name: 'bar',
            value: '\\bar{a}',
            icon: 'src/assets/latex/logic/bar.png'
        }, {
            name: 'dot',
            value: '\\dot{a}',
            icon: 'src/assets/latex/logic/dot.png'
        }, {
            name: 'breve',
            value: '\\breve{a}',
            icon: 'src/assets/latex/logic/breve.png'
        }, {
            name: 'plus',
            value: '+',
            icon: 'src/assets/latex/logic/plus.png'
        }, {
            name: 'times',
            value: '\\times',
            icon: 'src/assets/latex/logic/times.png'
        }, {
            name: 'cap',
            value: '\\cap',
            icon: 'src/assets/latex/logic/cap.png'
        }, {
            name: 'cup',
            value: '\\cup',
            icon: 'src/assets/latex/logic/cup.png'
        }, {
            name: 'vee',
            value: '\\vee',
            icon: 'src/assets/latex/logic/vee.png'
        }, {
            name: 'setminus',
            value: '\\setminus',
            icon: 'src/assets/latex/logic/setminus.png'
        }, {
            name: 'bigtriangleup',
            value: '\\bigtriangleup',
            icon: 'src/assets/latex/logic/bigtriangleup.png'
        }, {
            name: 'triangleright',
            value: '\\triangleright',
            icon: 'src/assets/latex/logic/triangleright.png'
        }, {
            name: 'rhd',
            value: '\\rhd',
            icon: 'src/assets/latex/logic/rhd.png'
        }, {
            name: 'unrhd',
            value: '\\unrhd',
            icon: 'src/assets/latex/logic/unrhd.png'
        }, {
            name: 'oplus',
            value: '\\oplus',
            icon: 'src/assets/latex/logic/oplus.png'
        }, {
            name: 'odot',
            value: '\\odot',
            icon: 'src/assets/latex/logic/odot.png'
        }, {
            name: 'uplus',
            value: '\\uplus',
            icon: 'src/assets/latex/logic/uplus.png'
        }, {
            name: 'ast',
            value: '\\ast',
            icon: 'src/assets/latex/logic/ast.png'
        }, {
            name: 'check',
            value: '\\check{a}',
            icon: 'src/assets/latex/logic/check.png'
        }, {
            name: 'vec',
            value: '\\vec{a}',
            icon: 'src/assets/latex/logic/vec.png'
        }, {
            name: 'ddot',
            value: '\\ddot{a}',
            icon: 'src/assets/latex/logic/ddot.png'
        }, {
            name: 'tilde',
            value: '\\tilde{a}',
            icon: 'src/assets/latex/logic/tilde.png'
        }, {
            name: 'minus',
            value: '-',
            icon: 'src/assets/latex/logic/minus.png'
        }, {
            name: 'div',
            value: '\\div',
            icon: 'src/assets/latex/logic/div.png'
        }, {
            name: 'sqcup',
            value: '\\sqcup',
            icon: 'src/assets/latex/logic/sqcup.png'
        }, {
            name: 'wedge',
            value: '\\wedge',
            icon: 'src/assets/latex/logic/wedge.png'
        }, {
            name: 'wr',
            value: '\\wr',
            icon: 'src/assets/latex/logic/wr.png'
        }, {
            name: 'bigtriangledown',
            value: '\\bigtriangledown',
            icon: 'src/assets/latex/logic/bigtriangledown.png'
        }, {
            name: 'triangleleft',
            value: '\\triangleleft',
            icon: 'src/assets/latex/logic/triangleleft.png'
        }, {
            name: 'lhd',
            value: '\\lhd',
            icon: 'src/assets/latex/logic/lhd.png'
        }, {
            name: 'unlhd',
            value: '\\unlhd',
            icon: 'src/assets/latex/logic/unlhd.png'
        }, {
            name: 'ominus',
            value: '\\ominus',
            icon: 'src/assets/latex/logic/ominus.png'
        }, {
            name: 'oslash',
            value: '\\oslash',
            icon: 'src/assets/latex/logic/oslash.png'
        }, {
            name: 'bigcirc',
            value: '\\bigcirc',
            icon: 'src/assets/latex/logic/bigcirc.png'
        }, {
            name: 'amalg',
            value: '\\amalg',
            icon: 'src/assets/latex/logic/amalg.png'
        }, {
            name: 'star',
            value: '\\star',
            icon: 'src/assets/latex/logic/star.png'
        }, {
            name: 'bullet',
            value: '\\bullet',
            icon: 'src/assets/latex/logic/bullet.png'
        }
    ],
    Symbols: [
        {
            name: 'ldots',
            value: '\\ldots',
            icon: 'src/assets/latex/symbols/ldots.png'
        }, {
            name: 'vdots',
            value: '\\vdots',
            icon: 'src/assets/latex/symbols/vdots.png'
        }, {
            name: 'mp',
            value: '\\mp',
            icon: 'src/assets/latex/symbols/mp.png'
        }, {
            name: 'times',
            value: '\\times',
            icon: 'src/assets/latex/symbols/times.png'
        }, {
            name: 'slash',
            value: '/',
            icon: 'src/assets/latex/symbols/slash.png'
        }, {
            name: 'or',
            value: '|',
            icon: 'src/assets/latex/symbols/or.png'
        }, {
            name: 'imath',
            value: '\\imath',
            icon: 'src/assets/latex/symbols/imath.png'
        }, {
            name: 'nabla',
            value: '\\nabla',
            icon: 'src/assets/latex/symbols/nabla.png'
        }, {
            name: 'top',
            value: '\\top',
            icon: 'src/assets/latex/symbols/top.png'
        }, {
            name: 'forall',
            value: '\\forall',
            icon: 'src/assets/latex/symbols/forall.png'
        }, {
            name: 'neg',
            value: '\\neg',
            icon: 'src/assets/latex/symbols/neg.png'
        }, {
            name: 'Re',
            value: '\\Re',
            icon: 'src/assets/latex/symbols/Re.png'
        }, {
            name: 'aleph',
            value: '\\aleph',
            icon: 'src/assets/latex/symbols/aleph.png'
        }, {
            name: 'ell',
            value: '\\ell',
            icon: 'src/assets/latex/symbols/ell.png'
        }, {
            name: 'wp',
            value: '\\wp',
            icon: 'src/assets/latex/symbols/wp.png'
        }, {
            name: 'prime',
            value: '\\prime',
            icon: 'src/assets/latex/symbols/prime.png'
        }, {
            name: 'surd',
            value: '\\surd',
            icon: 'src/assets/latex/symbols/surd.png'
        }, {
            name: 'natural',
            value: '\\natural',
            icon: 'src/assets/latex/symbols/natural.png'
        }, {
            name: 'Box',
            value: '\\Box',
            icon: 'src/assets/latex/symbols/Box.png'
        }, {
            name: 'clubsuit',
            value: '\\clubsuit',
            icon: 'src/assets/latex/symbols/clubsuit.png'
        }, {
            name: 'heartsuit',
            value: '\\heartsuit',
            icon: 'src/assets/latex/symbols/heartsuit.png'
        }, {
            name: 'cdots',
            value: '\\cdots',
            icon: 'src/assets/latex/symbols/cdots.png'
        }, {
            name: 'ddots',
            value: '\\ddots',
            icon: 'src/assets/latex/symbols/ddots.png'
        }, {
            name: 'pm',
            value: '\\pm',
            icon: 'src/assets/latex/symbols/pm.png'
        }, {
            name: 'ldots',
            value: '\\ldots',
            icon: 'src/assets/latex/symbols/ldots.png'
        }, {
            name: 'div',
            value: '\\div',
            icon: 'src/assets/latex/symbols/div.png'
        }, {
            name: 'backslash',
            value: '\\backslash',
            icon: 'src/assets/latex/symbols/backslash.png'
        }, {
            name: 'parallel',
            value: '\\|',
            icon: 'src/assets/latex/symbols/parallel.png'
        }, {
            name: 'jmath',
            value: '\\jmath',
            icon: 'src/assets/latex/symbols/jmath.png'
        }, {
            name: 'triangle',
            value: '\\triangle',
            icon: 'src/assets/latex/symbols/triangle.png'
        }, {
            name: 'bot',
            value: '\\bot',
            icon: 'src/assets/latex/symbols/bot.png'
        }, {
            name: 'exists',
            value: '\\exists',
            icon: 'src/assets/latex/symbols/exists.png'
        }, {
            name: 'flat',
            value: '\\flat',
            icon: 'src/assets/latex/symbols/flat.png'
        }, {
            name: 'infty',
            value: '\\infty',
            icon: 'src/assets/latex/symbols/infty.png'
        }, {
            name: 'Im',
            value: '\\Im',
            icon: 'src/assets/latex/symbols/Im.png'
        }, {
            name: 'hbar',
            value: '\\hbar',
            icon: 'src/assets/latex/symbols/hbar.png'
        }, {
            name: 'mho',
            value: '\\mho',
            icon: 'src/assets/latex/symbols/mho.png'
        }, {
            name: 'emptyset',
            value: '\\emptyset',
            icon: 'src/assets/latex/symbols/emptyset.png'
        }, {
            name: 'dot',
            value: '.',
            icon: 'src/assets/latex/symbols/dot.png'
        }, {
            name: 'angle',
            value: '\\angle',
            icon: 'src/assets/latex/symbols/angle.png'
        }, {
            name: 'sharp',
            value: '\\sharp',
            icon: 'src/assets/latex/symbols/sharp.png'
        }, {
            name: 'Diamond',
            value: '\\Diamond',
            icon: 'src/assets/latex/symbols/Diamond.png'
        }, {
            name: 'spadesuit',
            value: '\\spadesuit',
            icon: 'src/assets/latex/symbols/spadesuit.png'
        }, {
            name: 'diamondsuit',
            value: '\\diamondsuit',
            icon: 'src/assets/latex/symbols/diamondsuit.png'
        }
    ],
    Arrows: [
        {
            name: 'leftarrow',
            value: '\\leftarrow',
            icon: 'src/assets/latex/arrows/leftarrow.png'
        }, {
            name: 'Leftarrow',
            value: '\\Leftarrow',
            icon: 'src/assets/latex/arrows/cLeftarrow.png'
        }, {
            name: 'leftrightarrow',
            value: '\\leftrightarrow',
            icon: 'src/assets/latex/arrows/leftrightarrow.png'
        }, {
            name: 'mapsto',
            value: '\\mapsto',
            icon: 'src/assets/latex/arrows/mapsto.png'
        }, {
            name: 'leftharpoonup',
            value: '\\leftharpoonup',
            icon: 'src/assets/latex/arrows/leftharpoonup.png'
        }, {
            name: 'rightharpoonup',
            value: '\\rightharpoonup',
            icon: 'src/assets/latex/arrows/rightharpoonup.png'
        }, {
            name: 'longleftarrow',
            value: '\\longleftarrow',
            icon: 'src/assets/latex/arrows/longleftarrow.png'
        }, {
            name: 'Longleftarrow',
            value: '\\Longleftarrow',
            icon: 'src/assets/latex/arrows/cLongleftarrow.png'
        }, {
            name: 'longleftrightarrow',
            value: '\\longleftrightarrow',
            icon: 'src/assets/latex/arrows/longleftrightarrow.png'
        }, {
            name: 'uparrow',
            value: '\\uparrow',
            icon: 'src/assets/latex/arrows/uparrow.png'
        }, {
            name: 'downarrow',
            value: '\\downarrow',
            icon: 'src/assets/latex/arrows/downarrow.png'
        }, {
            name: 'updownarrow',
            value: '\\updownarrow',
            icon: 'src/assets/latex/arrows/updownarrow.png'
        }, {
            name: 'hookleftarrow',
            value: '\\hookleftarrow',
            icon: 'src/assets/latex/arrows/hookleftarrow.png'
        }, {
            name: 'rightleftharpoons',
            value: '\\rightleftharpoons',
            icon: 'src/assets/latex/arrows/rightleftharpoons.png'
        }, {
            name: 'nearrow',
            value: '\\nearrow',
            icon: 'src/assets/latex/arrows/nearrow.png'
        }, {
            name: 'searrow',
            value: '\\searrow',
            icon: 'src/assets/latex/arrows/searrow.png'
        }, {
            name: 'rightarrow',
            value: '\\rightarrow',
            icon: 'src/assets/latex/arrows/rightarrow.png'
        }, {
            name: 'Rightarrow',
            value: '\\Rightarrow',
            icon: 'src/assets/latex/arrows/cRightarrow.png'
        }, {
            name: 'leftarrow',
            value: '\\leftarrow',
            icon: 'src/assets/latex/arrows/leftarrow.png'
        }, {
            name: 'Leftrightarrow',
            value: '\\Leftrightarrow',
            icon: 'src/assets/latex/arrows/cLeftrightarrow.png'
        }, {
            name: 'longmapsto',
            value: '\\longmapsto',
            icon: 'src/assets/latex/arrows/longmapsto.png'
        }, {
            name: 'leftharpoondown',
            value: '\\leftharpoondown',
            icon: 'src/assets/latex/arrows/leftharpoondown.png'
        }, {
            name: 'rightharpoondown',
            value: '\\rightharpoondown',
            icon: 'src/assets/latex/arrows/rightharpoondown.png'
        }, {
            name: 'longrightarrow',
            value: '\\longrightarrow',
            icon: 'src/assets/latex/arrows/longrightarrow.png'
        }, {
            name: 'Longrightarrow',
            value: '\\Longrightarrow',
            icon: 'src/assets/latex/arrows/cLongrightarrow.png'
        }, {
            name: 'Longleftrightarrow',
            value: '\\Longleftrightarrow',
            icon: 'src/assets/latex/arrows/cLongleftrightarrow.png'
        }, {
            name: 'Uparrow',
            value: '\\Uparrow',
            icon: 'src/assets/latex/arrows/cUparrow.png'
        }, {
            name: 'Downarrow',
            value: '\\Downarrow',
            icon: 'src/assets/latex/arrows/cDownarrow.png'
        }, {
            name: 'Updownarrow',
            value: '\\Updownarrow',
            icon: 'src/assets/latex/arrows/cUpdownarrow.png'
        }, {
            name: 'hookrightarrow',
            value: '\\hookrightarrow',
            icon: 'src/assets/latex/arrows/hookrightarrow.png'
        }, {
            name: 'leadsto',
            value: '\\leadsto',
            icon: 'src/assets/latex/arrows/leadsto.png'
        }, {
            name: 'nwarrow',
            value: '\\nwarrow',
            icon: 'src/assets/latex/arrows/nwarrow.png'
        }, {
            name: 'swarrow',
            value: '\\swarrow',
            icon: 'src/assets/latex/arrows/swarrow.png'
        }
    ]
};
