# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
          authentication.userprovider:
              id: authentication.userprovider


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: authentication.userprovider
                csrf_token_generator: security.csrf.token_manager
                failure_path: /
                login_path: /
                check_path: check_login_ajax
                success_handler: user.main_login_handler
                failure_handler: user.main_login_handler
            logout:
                path: /logout
                target: /
                success_handler: user.logout_handler
                invalidate_session: false
            anonymous: true
            remember_me:
                secret: '%secret%'
                lifetime: 100000
                path: /
            switch_user:
                provider: authentication.userprovider
                parameter: _switch_user
                role: ROLE_ALLOWED_TO_SWITCH

        admin:
            pattern: ^/admin
            anonymous: ~
            form_login:
                csrf_provider: form.csrf_provider
                login_path: admin_login
                check_path: admin_login
            logout:
                path: /admin/logout
                target: /

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/lesson, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: [ROLE_TEACHER, ROLE_SUB_TEACHER] }
        - { path: ^/storage, roles: [ROLE_TEACHER, ROLE_SUB_TEACHER] }
        - { path: ^/subscriptions, role: ROLE_TEACHER }
        - { path: ^/teachers, role: ROLE_TEACHER }
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_RESELLER] }