# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.before_request_listener:
        class: AppBundle\EventListener\BeforeRequestListener
        arguments: ['@security.token_storage', '@router', '@plan.manager']
        tags:
              - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }